POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "sridevi",
    "password": "sridevi123"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "sridev",
    "password": "sridevi123"
}